spring:
  application:
    name: lesson8

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: users

  datasource:
    url: jdbc:postgresql://localhost:5432/somedb
    username: someuser
    password: somepass
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update