server:
  port: 0
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/somedb
    username: someuser
    password: somepass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/